name: Test and Coverage

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  test-and-coverage:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run TypeScript check
        run: npm run tsc

      - name: Run tests with coverage
        run: npm run test:coverage

      - name: Check if coverage file changed
        id: coverage-check
        run: |
          if git diff --quiet app/data/test-coverage.json; then
            echo "changed=false" >> $GITHUB_OUTPUT
          else
            echo "changed=true" >> $GITHUB_OUTPUT
          fi

      - name: Commit updated coverage file
        if: steps.coverage-check.outputs.changed == 'true' && github.event_name == 'pull_request'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add app/data/test-coverage.json
          git commit -m "Update test coverage data

          🤖 Auto-generated by GitHub Actions"

      - name: Push coverage update
        if: steps.coverage-check.outputs.changed == 'true' && github.event_name == 'pull_request'
        run: git push origin HEAD:${{ github.head_ref }}

      - name: Add PR comment with coverage summary
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            
            try {
              const coverageData = JSON.parse(fs.readFileSync('app/data/test-coverage.json', 'utf8'));
              const summary = coverageData.total;
              
              if (summary) {
                const comment = `## Test Coverage Summary
                
                | Metric | Coverage | Covered/Total |
                |--------|----------|---------------|
                | Statements | ${summary.statements.pct.toFixed(1)}% | ${summary.statements.covered}/${summary.statements.total} |
                | Branches | ${summary.branches.pct.toFixed(1)}% | ${summary.branches.covered}/${summary.branches.total} |
                | Functions | ${summary.functions.pct.toFixed(1)}% | ${summary.functions.covered}/${summary.functions.total} |
                | Lines | ${summary.lines.pct.toFixed(1)}% | ${summary.lines.covered}/${summary.lines.total} |
                
                🤖 Auto-generated coverage report`;
                
                // Find existing coverage comment
                const { data: comments } = await github.rest.issues.listComments({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  issue_number: context.issue.number,
                });
                
                const existingComment = comments.find(comment => 
                  comment.body.includes('## Test Coverage Summary')
                );
                
                if (existingComment) {
                  // Update existing comment
                  await github.rest.issues.updateComment({
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    comment_id: existingComment.id,
                    body: comment
                  });
                } else {
                  // Create new comment
                  await github.rest.issues.createComment({
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    issue_number: context.issue.number,
                    body: comment
                  });
                }
              }
            } catch (error) {
              console.log('Coverage file not found or invalid:', error.message);
            }